config/routes.rb
Rails.application.routes.draw do
  resources :products do
    get :new_modalbox, on: :collection
  end
  resources :types do
    get :new_modalbox, on: :collection
  end
  post 'import_items/create'

  post 'brochures/create'

  post 'brands/create'

  post 'vendors/create'

  post 'disiplines/create'

  put 'disiplines/update'

  post 'types/create'

  post 'products/create'

  post 'units/create'

  get 'import_items/update'

  get 'import_items/destroy'

  resources :item_price_letters
  resources :delivery_items
  resources :detail_items
  resources :price_items do
    collection do
      get 'new2/:items_id' => :new2, as: 'new2'
    end
  end
  resources :referensi_items
  resources :items do
    get :import, on: :collection
    get :getDataTemplate, on: :collection
    delete :destroy_multiple, on: :collection
  end
  resources :user_activities
  resources :disiplines do
    get :new_modalbox, on: :collection
    collection do
      get 'edit_modalbox/:id' => :edit_modalbox, as: 'edit_modalbox'
    end
  end
  resources :indonesia_villages
  resources :indonesia_districts
  resources :indonesia_cities
  resources :indonesia_provinces
  resources :vendors do
    get :new_modalbox, on: :collection
    collection do
      get 'detail_modalbox/:id' => :detail_modalbox, as: 'detail_modalbox'
    end
  end
  resources :currencies
  resources :references
  resources :price_letters do
    collection do
      get 'downloadLetter/:price_letter_id' => :downloadLetter, as: 'downloadLetter'
    end
  end
  resources :units do
    get :new_modalbox, on: :collection
  end
  resources :deliveries
  resources :brochures do
    collection do
      get 'new2/:items_id' => :new2, as: 'new2'
      get 'downloadBrochure/:brochure_id' => :downloadBrochure, as: 'downloadBrochure'
    end
  end
  resources :countries
  resources :brands do
    get :new_modalbox, on: :collection
  end
  devise_for :users, path: '', path_names: { sign_in: 'login_page', sign_out: 'logout'}
  resources :users
  resources :roles
  get 'errors/error_404'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#items_home'
  resources :dashboard do
    collection do
      get 'items_table/:disipline_id' => :items_table, as: 'items_table'
      get 'items_show/:id' => :items_show, as: 'items_show'
      get 'getItemsData/:type_id' => :getItemsData, as: 'getItemsData'
    end
    get :items_search, on: :collection
  end
  get 'dashboards/dashboard-social',
      to: 'dashboard#social',
      as: :dashboard_social

  # Smartadmin intel
  get 'smartadmin_intel/app_layouts',
      to: 'smartadmin_intel#app_layouts',
      as: :smartadmin_intel_app_layouts
  get 'smartadmin_intel/app_settings',
      to: 'smartadmin_intel#app_settings',
      as: :smartadmin_intel_app_settings
  get 'smartadmin_intel/prebuilt_skins',
      to: 'smartadmin_intel#prebuilt_skins',
      as: :smartadmin_intel_prebuilt_skins
  get 'outlook/inbox', to: 'outlook#inbox', as: :outlook_inbox

  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Graphs
  get 'graphs/flot_chart', to: 'graphs#flot_chart', as: :graphs_flot_chart
  get 'graphs/morris_charts',
      to: 'graphs#morris_charts',
      as: :graphs_morris_charts
  get 'graphs/sparklines', to: 'graphs#sparklines', as: :graphs_sparklines
  get 'graphs/easy_pie_charts',
      to: 'graphs#easy_pie_charts',
      as: :graphs_easy_pie_charts
  get 'graphs/dygraphs', to: 'graphs#dygraphs', as: :graphs_dygraphs
  get 'graphs/chart_js', to: 'graphs#chart_js', as: :graphs_chart_js
  get 'graphs/highchart_table',
      to: 'graphs#highchart_table',
      as: :graphs_highchart_table

  # Tables
  get 'tables/normal_tables',
      to: 'tables#normal_tables',
      as: :tables_normal_tables
  get 'tables/data_tables', to: 'tables#data_tables', as: :tables_data_tables
  get 'tables/jquery_grid', to: 'tables#jquery_grid', as: :tables_jquery_grid

  # Forms
  get 'forms/smart_form_elements',
      to: 'forms#smart_form_elements',
      as: :forms_smart_form_elements
  get 'forms/smart_form_layouts',
      to: 'forms#smart_form_layouts',
      as: :forms_smart_form_layouts
  get 'forms/smart_form_validations',
      to: 'forms#smart_form_validations',
      as: :forms_smart_form_validations
  get 'forms/bootstrap_form_elements',
      to: 'forms#bootstrap_form_elements',
      as: :forms_bootstrap_form_elements
  get 'forms/bootstrap_form_validation',
      to: 'forms#bootstrap_form_validation',
      as: :forms_bootstrap_form_validation
  get 'forms/form_plugins', to: 'forms#form_plugins', as: :forms_form_plugins
  get 'forms/wizards', to: 'forms#wizards', as: :forms_wizards
  get 'forms/bootstrap_editors',
      to: 'forms#bootstrap_editors',
      as: :forms_bootstrap_editors
  get 'forms/dropzone', to: 'forms#dropzone', as: :forms_dropzone
  get 'forms/image_cropping',
      to: 'forms#image_cropping',
      as: :forms_image_cropping
  get 'forms/ck_editor', to: 'forms#ck_editor', as: :forms_ck_editor

  # UI Elements
  get 'ui_elements/general_elements',
      to: 'ui_elements#general_elements',
      as: :ui_elements_general_elements
  get 'ui_elements/buttons', to: 'ui_elements#buttons', as: :ui_elements_buttons
  get 'ui_elements/icons/font_awesome',
      to: 'ui_elements#icons_font_awesome',
      as: :ui_elements_icons_font_awesome
  get 'ui_elements/icons/glyph_icons',
      to: 'ui_elements#icons_glyph_icons',
      as: :ui_elements_icons_glyph_icons
  get 'ui_elements/icons/flags',
      to: 'ui_elements#icons_flags',
      as: :ui_elements_icons_flags
  get 'ui_elements/grid', to: 'ui_elements#grid', as: :ui_elements_grid
  get 'ui_elements/tree_view',
      to: 'ui_elements#tree_view',
      as: :ui_elements_tree_view
  get 'ui_elements/nestable_lists',
      to: 'ui_elements#nestable_lists',
      as: :ui_elements_nestable_lists
  get 'ui_elements/jquery_ui',
      to: 'ui_elements#jquery_ui',
      as: :ui_elements_jquery_ui
  get 'ui_elements/typography',
      to: 'ui_elements#typography',
      as: :ui_elements_typography

  # Widgets
  get 'widgets/', to: 'widgets#index', as: :widgets

  # Cool Features
  get 'cool_features/calendar',
      to: 'cool_features#calendar',
      as: :cool_features_calendar
  get 'cool_features/gmap_skins',
      to: 'cool_features#gmap_skins',
      as: :cool_features_gmap_skins

  # App Views
  get 'app_views/projects', to: 'app_views#projects', as: :app_views_projects
  get 'app_views/blog', to: 'app_views#blog', as: :app_views_blog
  get 'app_views/gallery', to: 'app_views#gallery', as: :app_views_gallery
  get 'app_views/forum_layout_general_view',
      to: 'app_views#forum_layout_general_view',
      as: :app_views_forum_layout_general_view
  get 'app_views/forum_layout_topic_view',
      to: 'app_views#forum_layout_topic_view',
      as: :app_views_forum_layout_topic_view
  get 'app_views/forum_layout_post_view',
      to: 'app_views#forum_layout_post_view',
      as: :app_views_forum_layout_post_view
  get 'app_views/profile', to: 'app_views#profile', as: :app_views_profile
  get 'app_views/timeline', to: 'app_views#timeline', as: :app_views_timeline
  get 'app_views/search_page',
      to: 'app_views#search_page',
      as: :app_views_search_page

  # E-Commerce
  get 'e_commerce/orders', to: 'e_commerce#orders', as: :e_commerce_orders
  get 'e_commerce/products_view',
      to: 'e_commerce#products_view',
      as: :e_commerce_products_view
  get 'e_commerce/products_detail',
      to: 'e_commerce#products_detail',
      as: :e_commerce_products_detail

  # Miscellaneous
  get 'miscellaneous/pricing_tables',
      to: 'miscellaneous#pricing_tables',
      as: :miscellaneous_pricing_tables
  get 'miscellaneous/invoice',
      to: 'miscellaneous#invoice',
      as: :miscellaneous_invoice
  get 'miscellaneous/login',
      to: 'miscellaneous#login',
      as: :miscellaneous_login
  get 'miscellaneous/register',
      to: 'miscellaneous#register',
      as: :miscellaneous_register
  get 'miscellaneous/forgot_password',
      to: 'miscellaneous#forgot_password',
      as: :miscellaneous_forgot_password
  get 'miscellaneous/locked_screen',
      to: 'miscellaneous#locked_screen',
      as: :miscellaneous_locked_screen
  get 'miscellaneous/error_404',
      to: 'miscellaneous#error_404',
      as: :miscellaneous_error_404
  get 'miscellaneous/error_500',
      to: 'miscellaneous#error_500',
      as: :miscellaneous_error_500
  get 'miscellaneous/blank_page',
      to: 'miscellaneous#blank_page',
      as: :miscellaneous_blank_page

  # Smart chat API
  get 'smart_chat_api/',
      to: 'smart_chat_api#index',
      as: :smart_chat_api

  # Misc methods
  get '/home/set_locale', to: 'home#set_locale', as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'

  get '*path', to: 'errors#error_404', via: :all

end

app/models/price_letter.rb
class PriceLetter < ApplicationRecord
  has_many :price_item
end

app/controllers/price_letters_controller.rb
class PriceLettersController < ApplicationController
  before_action :set_price_letter, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  respond_to :html, :json
  include PriceLettersHelper
  # GET /price_letters
  # GET /price_letters.json
  def downloadLetter
    @getLetter = PriceLetter.find(params[:price_letter_id])
    send_file 'public/file/' + @getLetter.price_letter_path, :type => "application/pdf", :x_sendfile => true
  end

  def index
    @price_letters = PriceLetter.all
  end

  # GET /price_letters/1
  # GET /price_letters/1.json
  def show
  end

  # GET /price_letters/new
  def new
    @price_letter = PriceLetter.new
  end

  # GET /price_letters/1/edit
  def edit
  end

  # POST /price_letters
  # POST /price_letters.json
  def create
    @price_letter = PriceLetter.new(price_letter_params)

    respond_to do |format|
      params[:price_letter][:price_letter_path] ? @price_letter.price_letter_path = setFile : ""
      if @price_letter.save
        format.html { redirect_to @price_letter, notice: 'Price letter was successfully created.' }
        format.json { render :show, status: :created, location: @price_letter }
      else
        format.html { render :new }
        format.json { render json: @price_letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /price_letters/1
  # PATCH/PUT /price_letters/1.json
  def update
    respond_to do |format|
      params[:price_letter][:price_letter_path] ? @price_letter.price_letter_path = updateFile : ""
      if @price_letter.update(price_letter_params)
        format.html { redirect_to @price_letter, notice: 'Price letter was successfully updated.' }
        format.json { render :show, status: :ok, location: @price_letter }
      else
        format.html { render :edit }
        format.json { render json: @price_letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /price_letters/1
  # DELETE /price_letters/1.json
  def destroy
    getExistFile(params[:id])
    @price_letter.destroy
    respond_to do |format|
      format.html { redirect_to price_letters_url, notice: 'Price letter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price_letter
      @price_letter = PriceLetter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_letter_params
      params.require(:price_letter).permit(:price_letter_title, :price_letter_path)
    end
end

app/helpers/price_letters_helper.rb
module PriceLettersHelper
  def getExistFile(id)
    @logo = PriceLetter.find(id)
    file = @logo.price_letter_path
    if file.present?
      file_path = File.join('public/file/', file)
      File.delete(file_path) if File.exist?(file_path)
    end
  end

  def setFile
    folder_path = File.join('price_letters')
    folder = File.join('file')

    if !Dir.exist? folder_path
      FileUtils::mkdir_p (Rails.root.join('public', folder, folder_path))
    end

    uploaded_io = params[:price_letter][:price_letter_path]

    file_path = File.join(folder_path, uploaded_io.original_filename)
    File.open(Rails.root.join('public', folder, file_path), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    nama_file = file_path
    return nama_file
  end

  def updateFile
    @file = PriceLetter.find(params[:id])
    file = @file.price_letter_path
    file_path = File.join('public/file/', file)
    File.delete(file_path) if File.exist?(file_path)

    folder_path = File.join('price_letters')
    folder = File.join('file')

    if !Dir.exist? folder_path
      FileUtils::mkdir_p (Rails.root.join('public', folder, folder_path))
    end

    uploaded_io = params[:price_letter][:price_letter_path]

    file_path = File.join(folder_path, uploaded_io.original_filename)
    File.open(Rails.root.join('public', folder, file_path), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    nama_file = file_path
    return nama_file
  end
end

app/views/price_letters/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Form Price Letters</div>
  <div class="panel-body">
    <%= form_for @price_letter, html: {class: 'form-horizontal'} do |f| %>
      <% if @price_letter.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@price_letter.errors.count, "error") %> prohibited this price_letter from being saved:</h2>

          <ul>
            <% @price_letter.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <fieldset>
        <div class="form-group">
          <div class="col-sm-4 col-sm-offset-2">
            <%= f.label :price_letter_title %>
            <%= f.text_field :price_letter_title, class: 'form-control' %>
          </div>
        </div>
      </fieldset>

      <fieldset>
        <div class="form-group">
          <div class="col-sm-4 col-sm-offset-2">
            <%= f.label :price_letter_path %>
            <%= f.file_field :price_letter_path, class: "form-control", accept: 'file/*', onchange: "validateFiles(this);",
                             data: {max_file_size: 100.megabytes}%>
          </div>
        </div>
      </fieldset>

      <script type="text/javascript">
          function validateFiles(inputFile) {
              var maxExceededMessage = "This file exceeds the maximum allowed file size (100 MB)";
              var extErrorMessage = "Only doc file with extension: .pdf or .docs is allowed";
              var allowedExtension = ["pdf","docs"];

              var extName;
              var maxFileSize = $(inputFile).data('max-file-size');
              var sizeExceeded = false;
              var extError = false;

              $.each(inputFile.files, function () {
                  if (this.size && maxFileSize && this.size > parseInt(maxFileSize)) {
                      sizeExceeded = true;
                  }
                  ;
                  extName = this.name.split('.').pop();
                  if ($.inArray(extName, allowedExtension) == -1) {
                      extError = true;
                  }
                  ;
              });
              if (sizeExceeded) {
                  window.alert(maxExceededMessage);
                  $(inputFile).val('');
              }
              ;

              if (extError) {
                  window.alert(extErrorMessage);
                  $(inputFile).val('');
              }
              ;
          }
      </script>

      <fieldset>
        <div class="form-group">
          <div class="col-sm-4 col-sm-offset-2">
            <%= link_to 'Cancel', price_letters_path, class: 'btn btn-default' %>
            <button type="submit" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/price_letters/edit.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">

  <span class="ribbon-button-alignment">
    <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh" rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
      <i class="fa fa-refresh"></i>
    </span>
  </span>

    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li>Home</li>
      <li>Tables</li>
      <li>Normal Tables</li>
    </ol>
    <!-- end breadcrumb -->

    <!-- You can also add more buttons to the
    ribbon for further usability

    Example below:

    <span class="ribbon-button-alignment pull-right">
    <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
    <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
    <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
    </span> -->

  </div>
  <!-- END RIBBON -->
<% end %>
<div class="content">
  <h1>Editing Price Letter</h1>

  <%= render 'form', price_letter: @price_letter %>

  <%= link_to 'Show', @price_letter %> |
  <%= link_to 'Back', price_letters_path %>
</div>

app/views/price_letters/index.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">

  <span class="ribbon-button-alignment">
    <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh" rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
      <i class="fa fa-refresh"></i>
    </span>
  </span>

    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li>Admin Panel</li>
      <li>Data Master</li>
      <li>Price Letter Lists</li>
    </ol>
    <!-- end breadcrumb -->

    <!-- You can also add more buttons to the
    ribbon for further usability

    Example below:

    <span class="ribbon-button-alignment pull-right">
    <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
    <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
    <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
    </span> -->

  </div>
  <!-- END RIBBON -->
<% end %>
<div id="content">
  <div class="page-header">
    <%= link_to new_price_letter_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Price Letter
    <% end %>

    <h1>Listing Unit</h1>
  </div>
  <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-2" data-widget-editbutton="false">
    <!-- widget options:
    usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

    data-widget-colorbutton="false"
    data-widget-editbutton="false"
    data-widget-togglebutton="false"
    data-widget-deletebutton="false"
    data-widget-fullscreenbutton="false"
    data-widget-custombutton="false"
    data-widget-collapsed="true"
    data-widget-sortable="false"

    -->
    <header>
      <span class="widget-icon"> <i class="fa fa-table"></i> </span>
    </header>

    <!-- widget div-->
    <div>

      <!-- widget edit box -->
      <div class="jarviswidget-editbox">
        <!-- This area used as dropdown edit box -->

      </div>
      <div class="table-responsive">
        <table id="datatable_col_reorder" class="table table-striped table-bordered table-hover" width="100%">
          <thead>
          <tr>
            <th>Price letter title</th>
            <th>Price letter path</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
          </thead>

          <tbody>
          <% @price_letters.each do |price_letter| %>
            <tr>
              <td><%= price_letter.price_letter_title %></td>
              <td><%= price_letter.price_letter_path %></td>
              <td><%= link_to '', price_letter, class: 'fa fa-eye btn btn-sm btn-success', title: "Show" %></td>
              <td><%= link_to '', edit_price_letter_path(price_letter), class: 'fa fa-pencil btn btn-sm btn-warning', title: "Edit" %></td>
              <td><%= link_to '', price_letter, method: :delete, data: {confirm: 'Are you sure?'}, class: 'fa fa-trash btn btn-sm btn-danger', title: "Delete" %></td>
              <td><%= link_to '', downloadLetter_price_letters_path(price_letter), class: 'fa fa-download btn btn-sm btn-danger', title: "Download" %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<% content_for :scripts do %>
  <script type="text/javascript">

      // DO NOT REMOVE : GLOBAL FUNCTIONS!

      $(document).ready(function () {

          pageSetUp();

          /* // DOM Position key index //

           l - Length changing (dropdown)
           f - Filtering input (search)
           t - The Table! (datatable)
           i - Information (records)
           p - Pagination (paging)
           r - pRocessing
           < and > - div elements
           <"#id" and > - div with an id
           <"class" and > - div with a class
           <"#id.class" and > - div with an id and class

           Also see: http://legacy.datatables.net/usage/features
           */

          /* BASIC ;*/
          var responsiveHelper_dt_basic = undefined;
          var responsiveHelper_datatable_col_reorder = undefined;

          var breakpointDefinition = {
              tablet: 1024,
              phone: 480
          };

          $('#dt_basic').dataTable({
              "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>" +
                  "t" +
                  "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
              "autoWidth": true,
              "oLanguage": {
                  "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
              },
              "preDrawCallback": function () {
                  // Initialize the responsive datatables helper once.
                  if (!responsiveHelper_dt_basic) {
                      responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#dt_basic'), breakpointDefinition);
                  }
              },
              "rowCallback": function (nRow) {
                  responsiveHelper_dt_basic.createExpandIcon(nRow);
              },
              "drawCallback": function (oSettings) {
                  responsiveHelper_dt_basic.respond();
              }
          });

          /* END BASIC */

          /* COLUMN SHOW - HIDE */
          $('#datatable_col_reorder').dataTable({
              "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'C>r>" +
                  "t" +
                  "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
              "autoWidth": true,
              "oLanguage": {
                  "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
              },
              "preDrawCallback": function () {
                  // Initialize the responsive datatables helper once.
                  if (!responsiveHelper_datatable_col_reorder) {
                      responsiveHelper_datatable_col_reorder = new ResponsiveDatatablesHelper($('#datatable_col_reorder'), breakpointDefinition);
                  }
              },
              "rowCallback": function (nRow) {
                  responsiveHelper_datatable_col_reorder.createExpandIcon(nRow);
              },
              "drawCallback": function (oSettings) {
                  responsiveHelper_datatable_col_reorder.respond();
              }
          });

          /* END COLUMN SHOW - HIDE */

      })

  </script>
<% end %>

app/views/price_letters/new.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">

  <span class="ribbon-button-alignment">
    <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh" rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
      <i class="fa fa-refresh"></i>
    </span>
  </span>

    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li>Home</li>
      <li>Tables</li>
      <li>Normal Tables</li>
    </ol>
    <!-- end breadcrumb -->

    <!-- You can also add more buttons to the
    ribbon for further usability

    Example below:

    <span class="ribbon-button-alignment pull-right">
    <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
    <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
    <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
    </span> -->

  </div>
  <!-- END RIBBON -->
<% end %>
<div class="content">
  <h1>New Price Letter</h1>

  <%= render 'form', price_letter: @price_letter %>

  <%= link_to 'Back', price_letters_path %>
</div>

app/views/price_letters/show.html.erb
<div id="content">
  <div class="page-header">
    <%= link_to price_letters_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back
    <% end %>
    <%= link_to edit_price_letter_path(@price_letter), class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Edit
    <% end %>
    <h1>Show Price Letter</h1>
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            Detail Price Letter
          </div>
          <div class="panel-body">
            <table class="table table-bordered table-striped table-hover">
              <tbody>
              <tr>
                <td>Price letter title:</td>
                <td><%= @price_letter.price_letter_title %></td>
              </tr>
              <tr>
                <td>Price letter path:</td>
                <td><%= @price_letter.price_letter_path %></td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>